let products = [
    {
      id: "001",
      name: "Apples",
      price: 3,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/apples.jpg",
      quantity: 0,
    },
    {
      id: "002",
      name: "Bananas",
      price: 2,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/bananas.jpg",
      quantity: 0,
    },
    {
      id: "003",
      name: "Blueberries",
      price: 7,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/blueberries.jpg",
      quantity: 0,
    },
    {
      id: "004",
      name: "Grapes",
      price: 5,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/grapes.jpg",
      quantity: 0,
    },
    {
      id: "005",
      name: "Oranges",
      price: 4,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/oranges.jpg",
      quantity: 0,
    },
    {
      id: "006",
      name: "Peaches",
      price: 7,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/peaches.jpg",
      quantity: 0,
    },
    {
      id: "007",
      name: "Raspberries",
      price: 9,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/raspberries.jpg",
      quantity: 0,
    },
    {
      id: "008",
      name: "Strawberries",
      price: 8,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/strawberries.jpg",
      quantity: 0,
    },
    {
      id: "009",
      name: "Watermelons",
      price: 14,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/watermelons.jpg",
      quantity: 0,
    },
  ];