let shopItemsData = [
    {
      id: "apples",
      name: "Apples",
      price: 3,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/apples.jpg",
    },
    {
      id: "bananas",
      name: "Bananas",
      price: 2,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/bananas.jpg",
    },
    {
      id: "blueberries",
      name: "Blueberries",
      price: 7,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/blueberries.jpg",
    },
    {
      id: "grapes",
      name: "Grapes",
      price: 5,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/grapes.jpg",
    },
    {
      id: "oranges",
      name: "Oranges",
      price: 4,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/oranges.jpg",
    },
    {
      id: "peaches",
      name: "Peaches",
      price: 7,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/peaches.jpg",
    },
    {
      id: "raspberries",
      name: "Raspberries",
      price: 9,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/raspberries.jpg",
    },
    {
      id: "strawberries",
      name: "Strawberries",
      price: 8,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/strawberries.jpg",
    },
    {
      id: "watermelons",
      name: "Watermelons",
      price: 14,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/watermelons.jpg",
    },
  ];